#!/bin/bash
cat << 'DTS_EOF' > openai-oxide-node/index.d.ts
/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface ResponseFormat {
  type: string;
}

export interface ChatCompletionRequest {
  model: string;
  messages: Array<any>;
  temperature?: number;
  max_tokens?: number;
  top_p?: number;
  frequency_penalty?: number;
  presence_penalty?: number;
  stop?: string | string[];
  stream?: boolean;
  response_format?: ResponseFormat;
  tools?: Array<any>;
  tool_choice?: string | object;
}

export interface ResponseCreateRequest {
  model: string;
  input: string;
  instructions?: string;
  temperature?: number;
  tools?: Array<any>;
}

export declare class Client {
  constructor()
  /** Make a complete request to the Responses API */
  createResponse(request: ResponseCreateRequest | any): Promise<any>
  /** Stream a response from the Responses API */
  createStream(request: ResponseCreateRequest | any, tsfn: (err: Error | null, event: any | null) => void): Promise<void>
  /** Open a persistent WebSocket session */
  wsSession(): Promise<NodeWsSession>
}

export declare class NodeWsSession {
  /** Send a request via the WebSocket connection */
  send(model: string, input: string): Promise<any>
  /** Close the WebSocket connection */
  close(): Promise<void>
}
DTS_EOF
echo "DTS patched"
