// AUTO-GENERATED by py2rust — do not edit.
// Re-generate: python3 scripts/py2rust.py sync <python_dir> <rust_dir>
// Domain: beta
#![allow(unused_imports)]

use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ToolResourcesCodeInterpreter {
    /// A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_ids: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ToolResourcesFileSearch {
    /// The ID of the
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub vector_store_ids: Option<Vec<String>>,
}

/// A set of resources that are used by the assistant's tools.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ToolResources {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub code_interpreter: Option<ToolResourcesCodeInterpreter>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_search: Option<ToolResourcesFileSearch>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct AssistantCreateParams {
    /// ID of the model to use.
    pub model: String,
    /// The description of the assistant. The maximum length is 512 characters.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,
    /// The system instructions that the assistant uses.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub instructions: Option<String>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// The name of the assistant. The maximum length is 256 characters.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    /// Constrains effort on reasoning for
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reasoning_effort: Option<serde_json::Value>,
    /// Specifies the format that the model must output.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub response_format: Option<serde_json::Value>,
    /// What sampling temperature to use, between 0 and 2.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub temperature: Option<f64>,
    /// A set of resources that are used by the assistant's tools.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_resources: Option<ToolResources>,
    /// A list of tool enabled on the assistant.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tools: Option<Vec<serde_json::Value>>,
    /// An alternative to sampling with temperature, called nucleus sampling, where the
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub top_p: Option<f64>,
}

/// The default strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ToolResourcesFileSearchVectorStoreChunkingStrategyAuto {
    /// Always `auto`.
    #[serde(rename = "type")]
    pub type_: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic {
    /// The number of tokens that overlap between chunks. The default value is `400`.
    pub chunk_overlap_tokens: i64,
    /// The maximum number of tokens in each chunk.
    pub max_chunk_size_tokens: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ToolResourcesFileSearchVectorStoreChunkingStrategyStatic {
    #[serde(rename = "static")]
    pub static_: ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic,
    /// Always `static`.
    #[serde(rename = "type")]
    pub type_: String,
}

pub type ToolResourcesFileSearchVectorStoreChunkingStrategy = serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ToolResourcesFileSearchVectorStore {
    /// The chunking strategy used to chunk the file(s).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub chunking_strategy: Option<ToolResourcesFileSearchVectorStoreChunkingStrategy>,
    /// A list of [file](https://platform.openai.com/docs/api-reference/files) IDs to
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_ids: Option<serde_json::Value>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum AssistantListParamsOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum AssistantResponseFormatOption {
    Auto,
}

/// Occurs when a new [thread](https://platform.openai.com/docs/api-reference/threads/object) is created.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadCreated {
    /// Represents a thread that contains
    pub data: Thread,
    pub event: String,
    /// Whether to enable input audio transcription.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub enabled: Option<bool>,
}

/// Occurs when a new [run](https://platform.openai.com/docs/api-reference/runs/object) is created.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunCreated {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) moves to a `queued` status.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunQueued {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) moves to an `in_progress` status.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunInProgress {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) moves to a `requires_action` status.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunRequiresAction {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) is completed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunCompleted {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) ends with status `incomplete`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunIncomplete {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) fails.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunFailed {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) moves to a `cancelling` status.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunCancelling {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) is cancelled.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunCancelled {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run](https://platform.openai.com/docs/api-reference/runs/object) expires.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunExpired {
    /// Represents an execution run on a
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run step](https://platform.openai.com/docs/api-reference/run-steps/step-object) is created.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunStepCreated {
    /// Represents a step in execution of a run.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run step](https://platform.openai.com/docs/api-reference/run-steps/step-object) moves to an `in_progress` state.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunStepInProgress {
    /// Represents a step in execution of a run.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when parts of a [run step](https://platform.openai.com/docs/api-reference/run-steps/step-object) are being streamed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunStepDelta {
    /// Represents a run step delta i.e.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run step](https://platform.openai.com/docs/api-reference/run-steps/step-object) is completed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunStepCompleted {
    /// Represents a step in execution of a run.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run step](https://platform.openai.com/docs/api-reference/run-steps/step-object) fails.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunStepFailed {
    /// Represents a step in execution of a run.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run step](https://platform.openai.com/docs/api-reference/run-steps/step-object) is cancelled.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunStepCancelled {
    /// Represents a step in execution of a run.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [run step](https://platform.openai.com/docs/api-reference/run-steps/step-object) expires.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadRunStepExpired {
    /// Represents a step in execution of a run.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [message](https://platform.openai.com/docs/api-reference/messages/object) is created.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadMessageCreated {
    /// Represents a message within a
    pub data: Message,
    pub event: String,
}

/// Occurs when a [message](https://platform.openai.com/docs/api-reference/messages/object) moves to an `in_progress` state.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadMessageInProgress {
    /// Represents a message within a
    pub data: Message,
    pub event: String,
}

/// Occurs when parts of a [Message](https://platform.openai.com/docs/api-reference/messages/object) are being streamed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadMessageDelta {
    /// Represents a message delta i.e.
    pub data: serde_json::Value,
    pub event: String,
}

/// Occurs when a [message](https://platform.openai.com/docs/api-reference/messages/object) is completed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadMessageCompleted {
    /// Represents a message within a
    pub data: Message,
    pub event: String,
}

/// Occurs when a [message](https://platform.openai.com/docs/api-reference/messages/object) ends before it is completed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadMessageIncomplete {
    /// Represents a message within a
    pub data: Message,
    pub event: String,
}

/// Occurs when an [error](https://platform.openai.com/docs/guides/error-codes#api-errors) occurs. This can happen due to an internal server error or a timeout.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ErrorEvent {
    pub data: serde_json::Value,
    pub event: String,
}

pub type AssistantStreamEvent = serde_json::Value;

pub type AssistantTool = serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum AssistantToolChoiceType {
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "code_interpreter")]
    CodeInterpreter,
    #[serde(rename = "file_search")]
    FileSearch,
}

/// Specifies a tool the model should use.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct AssistantToolChoice {
    /// The type of the tool. If type is `function`, the function name must be set
    #[serde(rename = "type")]
    pub type_: AssistantToolChoiceType,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub function: Option<AssistantToolChoiceFunction>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct AssistantToolChoiceFunction {
    /// The name of the function to call.
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum AssistantToolChoiceOption {
    None,
    Auto,
    Required,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct AssistantUpdateParams {
    /// The description of the assistant. The maximum length is 512 characters.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,
    /// The system instructions that the assistant uses.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub instructions: Option<String>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// ID of the model to use.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    /// The name of the assistant. The maximum length is 256 characters.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    /// Constrains effort on reasoning for
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reasoning_effort: Option<serde_json::Value>,
    /// Specifies the format that the model must output.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub response_format: Option<serde_json::Value>,
    /// What sampling temperature to use, between 0 and 2.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub temperature: Option<f64>,
    /// A set of resources that are used by the assistant's tools.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_resources: Option<ToolResources>,
    /// A list of tool enabled on the assistant.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tools: Option<Vec<serde_json::Value>>,
    /// An alternative to sampling with temperature, called nucleus sampling, where the
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub top_p: Option<f64>,
}

/// Tracing settings applied to the workflow.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct Tracing {
    /// Indicates whether tracing is enabled.
    pub enabled: bool,
}

/// Workflow metadata and state returned for the session.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ChatKitWorkflow {
    /// Identifier of the workflow backing the session.
    pub id: String,
    /// State variable key-value pairs applied when invoking the workflow.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub state_variables: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Tracing settings applied to the workflow.
    pub tracing: Tracing,
    /// Specific workflow version used for the session.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub version: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct CodeInterpreterTool {
    /// The type of tool being defined: `code_interpreter`
    #[serde(rename = "type")]
    pub type_: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileSearchRankingOptionsRanker {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "default_2024_08_21")]
    Default20240821,
}

/// Overrides for the file search tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileSearch {
    /// The maximum number of results the file search tool should output.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_num_results: Option<i64>,
    /// The ranking options for the file search.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub ranking_options: Option<FileSearchRankingOptions>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileSearchTool {
    /// The type of tool being defined: `file_search`
    #[serde(rename = "type")]
    pub type_: String,
    /// Overrides for the file search tool.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_search: Option<FileSearch>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FunctionTool {
    pub function: serde_json::Value,
    /// The type of tool being defined: `function`
    #[serde(rename = "type")]
    pub type_: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadCreateAndRunParamsBase {
    /// The ID of the
    pub assistant_id: String,
    /// Override the default system message of the assistant.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub instructions: Option<String>,
    /// The maximum number of completion tokens that may be used over the course of the
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_completion_tokens: Option<i64>,
    /// The maximum number of prompt tokens that may be used over the course of the run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_prompt_tokens: Option<i64>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// The ID of the [Model](https://platform.openai.com/docs/api-reference/models) to
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    /// Whether to enable
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub parallel_tool_calls: Option<bool>,
    /// Specifies the format that the model must output.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub response_format: Option<serde_json::Value>,
    /// What sampling temperature to use, between 0 and 2.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub temperature: Option<f64>,
    /// Options to create a new thread.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub thread: Option<Thread>,
    /// Controls which (if any) tool is called by the model. `none` means the model will
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_choice: Option<serde_json::Value>,
    /// A set of resources that are used by the assistant's tools.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_resources: Option<ToolResources>,
    /// Override the tools the assistant can use for this run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tools: Option<Vec<serde_json::Value>>,
    /// An alternative to sampling with temperature, called nucleus sampling, where the
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub top_p: Option<f64>,
    /// Controls for how a thread will be truncated prior to the run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub truncation_strategy: Option<TruncationStrategy>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadMessageAttachmentToolFileSearch {
    /// The type of tool being defined: `file_search`
    #[serde(rename = "type")]
    pub type_: String,
}

pub type ThreadMessageAttachmentTool = serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadMessageAttachment {
    /// The ID of the file to attach to the message.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_id: Option<String>,
    /// The tools to add this file to.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tools: Option<Vec<ThreadMessageAttachmentTool>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum ThreadMessageRole {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadToolResourcesCodeInterpreter {
    /// A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_ids: Option<serde_json::Value>,
}

/// The default strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadToolResourcesFileSearchVectorStoreChunkingStrategyAuto {
    /// Always `auto`.
    #[serde(rename = "type")]
    pub type_: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic {
    /// The number of tokens that overlap between chunks. The default value is `400`.
    pub chunk_overlap_tokens: i64,
    /// The maximum number of tokens in each chunk.
    pub max_chunk_size_tokens: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadToolResourcesFileSearchVectorStoreChunkingStrategyStatic {
    #[serde(rename = "static")]
    pub static_: ThreadToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic,
    /// Always `static`.
    #[serde(rename = "type")]
    pub type_: String,
}

pub type ThreadToolResourcesFileSearchVectorStoreChunkingStrategy = serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadToolResourcesFileSearchVectorStore {
    /// The chunking strategy used to chunk the file(s).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub chunking_strategy: Option<ThreadToolResourcesFileSearchVectorStoreChunkingStrategy>,
    /// A list of [file](https://platform.openai.com/docs/api-reference/files) IDs to
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_ids: Option<serde_json::Value>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadToolResourcesFileSearch {
    /// The
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub vector_store_ids: Option<serde_json::Value>,
    /// A helper to create a
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub vector_stores: Option<Vec<ThreadToolResourcesFileSearchVectorStore>>,
}

/// A set of resources that are made available to the assistant's tools in this thread. The resources are specific to the type of tool. For example, the `code_interpreter` tool requires a list of file IDs, while the `file_search` tool requires a list of vector store IDs.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadToolResources {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub code_interpreter: Option<ThreadToolResourcesCodeInterpreter>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_search: Option<ThreadToolResourcesFileSearch>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum TruncationStrategyType {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "last_messages")]
    LastMessages,
}

/// Controls for how a thread will be truncated prior to the run.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct TruncationStrategy {
    /// The truncation strategy to use for the thread.
    #[serde(rename = "type")]
    pub type_: TruncationStrategyType,
    /// The number of most recent messages from the thread when constructing the context
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub last_messages: Option<i64>,
}

pub type ThreadCreateAndRunParams = serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadCreateParams {
    /// A list of [messages](https://platform.openai.com/docs/api-reference/messages) to
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub messages: Option<Vec<Message>>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// A set of resources that are made available to the assistant's tools in this
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_resources: Option<ToolResources>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct MessageAttachmentToolFileSearch {
    /// The type of tool being defined: `file_search`
    #[serde(rename = "type")]
    pub type_: String,
}

pub type MessageAttachmentTool = serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct MessageAttachment {
    /// The ID of the file to attach to the message.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_id: Option<String>,
    /// The tools to add this file to.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tools: Option<Vec<MessageAttachmentTool>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum MessageRole {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ThreadUpdateParams {
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// A set of resources that are made available to the assistant's tools in this
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_resources: Option<ToolResources>,
}
