// AUTO-GENERATED by py2rust — do not edit.
// Re-generate: python3 scripts/py2rust.py sync <python_dir> <rust_dir>
// Domain: fine_tuning
#![allow(unused_imports)]

use super::*;
use serde::{Deserialize, Serialize};

/// The hyperparameters used for the DPO fine-tuning job.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct DpoHyperparameters {
    /// Number of examples in each batch.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub batch_size: Option<String>,
    /// The beta value for the DPO method.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub beta: Option<String>,
    /// Scaling factor for the learning rate.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub learning_rate_multiplier: Option<String>,
    /// The number of epochs to train the model for.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub n_epochs: Option<String>,
}

/// Configuration for the DPO fine-tuning method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct DpoMethod {
    /// The hyperparameters used for the DPO fine-tuning job.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub hyperparameters: Option<DpoHyperparameters>,
}

/// For fine-tuning jobs that have `failed`, this will contain more information on the cause of the failure.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct JobError {
    /// A machine-readable error code.
    pub code: String,
    /// A human-readable error message.
    pub message: String,
    /// The parameter that was invalid, usually `training_file` or `validation_file`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub param: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum MethodType {
    #[serde(rename = "supervised")]
    Supervised,
    #[serde(rename = "dpo")]
    Dpo,
    #[serde(rename = "reinforcement")]
    Reinforcement,
}

/// The method used for fine-tuning.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct Method {
    /// The type of method. Is either `supervised`, `dpo`, or `reinforcement`.
    #[serde(rename = "type")]
    pub type_: MethodType,
    /// Configuration for the DPO fine-tuning method.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub dpo: Option<DpoMethod>,
    /// Configuration for the reinforcement fine-tuning method.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reinforcement: Option<ReinforcementMethod>,
    /// Configuration for the supervised fine-tuning method.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub supervised: Option<SupervisedMethod>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FineTuningJobStatus {
    #[serde(rename = "validating_files")]
    ValidatingFiles,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FineTuningJobEventLevel {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warn")]
    Warn,
    #[serde(rename = "error")]
    Error,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FineTuningJobEventType {
    #[serde(rename = "message")]
    Message,
    #[serde(rename = "metrics")]
    Metrics,
}

/// The settings for your integration with Weights and Biases.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FineTuningJobWandbIntegration {
    /// The name of the project that the new run will be created under.
    pub project: String,
    /// The entity to use for the run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub entity: Option<String>,
    /// A display name to set for the run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    /// A list of tags to be attached to the newly created run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tags: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FineTuningJobWandbIntegrationObject {
    /// The type of the integration being enabled for the fine-tuning job
    #[serde(rename = "type")]
    pub type_: String,
    /// The settings for your integration with Weights and Biases.
    pub wandb: FineTuningJobWandbIntegration,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct JobCreateParams {
    /// The name of the model to fine-tune.
    pub model: Option<String>,
    /// The ID of an uploaded file that contains training data.
    pub training_file: String,
    /// The hyperparameters used for the fine-tuning job. This value is now deprecated
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub hyperparameters: Option<Hyperparameters>,
    /// A list of integrations to enable for your fine-tuning job.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub integrations: Option<Vec<Integration>>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// The method used for fine-tuning.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub method: Option<Method>,
    /// The seed controls the reproducibility of the job.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub seed: Option<i64>,
    /// A string of up to 64 characters that will be added to your fine-tuned model
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub suffix: Option<String>,
    /// The ID of an uploaded file that contains validation data.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub validation_file: Option<String>,
}

/// The settings for your integration with Weights and Biases.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct IntegrationWandb {
    /// The name of the project that the new run will be created under.
    pub project: String,
    /// The entity to use for the run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub entity: Option<String>,
    /// A display name to set for the run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    /// A list of tags to be attached to the newly created run.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tags: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct Integration {
    /// The type of integration to enable.
    #[serde(rename = "type")]
    pub type_: String,
    /// The settings for your integration with Weights and Biases.
    pub wandb: IntegrationWandb,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct JobListEventsParams {
    /// Identifier for the last event from the previous pagination request.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// Number of events to retrieve.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct JobListParams {
    /// Identifier for the last job from the previous pagination request.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// Number of fine-tuning jobs to retrieve.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub limit: Option<i64>,
    /// Optional metadata filter.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum ReinforcementHyperparametersReasoningEffort {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
}

/// The hyperparameters used for the reinforcement fine-tuning job.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ReinforcementHyperparameters {
    /// Number of examples in each batch.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub batch_size: Option<String>,
    /// Multiplier on amount of compute used for exploring search space during training.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub compute_multiplier: Option<String>,
    /// The number of training steps between evaluation runs.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub eval_interval: Option<String>,
    /// Number of evaluation samples to generate per training step.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub eval_samples: Option<String>,
    /// Scaling factor for the learning rate.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub learning_rate_multiplier: Option<String>,
    /// The number of epochs to train the model for.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub n_epochs: Option<String>,
    /// Level of reasoning effort.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reasoning_effort: Option<ReinforcementHyperparametersReasoningEffort>,
}

pub type Grader = serde_json::Value;

/// Configuration for the reinforcement fine-tuning method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ReinforcementMethod {
    /// The grader used for the fine-tuning job.
    pub grader: Grader,
    /// The hyperparameters used for the reinforcement fine-tuning job.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub hyperparameters: Option<ReinforcementHyperparameters>,
}

/// The hyperparameters used for the fine-tuning job.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct SupervisedHyperparameters {
    /// Number of examples in each batch.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub batch_size: Option<String>,
    /// Scaling factor for the learning rate.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub learning_rate_multiplier: Option<String>,
    /// The number of epochs to train the model for.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub n_epochs: Option<String>,
}

/// Configuration for the supervised fine-tuning method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct SupervisedMethod {
    /// The hyperparameters used for the fine-tuning job.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub hyperparameters: Option<SupervisedHyperparameters>,
}
